{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "common.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - from:
        {{- range .Values.networkPolicy.ingress.from }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.ingress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.egress.enabled }}
    - to:
        {{- range .Values.networkPolicy.egress.to }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.egress.ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
    {{- end }}
{{- end }}
